insert into  db_mindloose.nivel
values 
(0,"0-0"),
(1,"0-30"),
(2,"31-60"),
(3,"61-85"),
(4,"86-110"),
(5,"111-125");
insert into  db_mindloose.comentarios
values 
(1,"Todavia hay mucha area de mejora.","Intenta realizar después los retos pendientes.",1),
(2,"Aun puedes corregirlo." ,"No te frustres por no poder completar os retos.",1),
(3,"Vas por buen camino !suerte¡.","Consulta tu progreso regularmente.",1),
(4,"Tú puedes casi llegas.","Puedes ir con especialistas si es de gravedad.",1),
(5,"Llegaste al final de tu primer escalón","Empieza con familiares para confiar en ti.",1),
(6,"Bienvenido al verdadero inicio del camino.","Puedes cambiar tu contraseña en cuenta.",2),
(7,"Tu progreso es sobreesaliente.","Si requieres asistencia puedes contactarnos.",2),
(8,"Te sientes mejor?","Integra los retos diariamente para diciplinarte.",2),
(9,"Te sientes comodo hoy?","Ayuda a otros que sufran de lo mismo.",2),
(10,"Te lo estas ganando a pulso","Se tu no intentes cambiar.",2),
(11,"Se nota tu confianza","Romper tu rutina regularmente ayudara.",3),
(12,"Feliz por el ascenso ¿verdad?","Cambia por ti no por externos.",3),
(13,"Como el siente el nivel 2?","Conserva tu personalidad.",3),
(14,"Casi llegas.","Si buscas pareja necesitaras confianza.",3),
(15,"El final de este nivel :D.","Los amigo te ayudaran en momentos duros.",3),
(16,"Estas cerca del final tu puedes.","Recuerda tu pones tu límite",4),
(17,"Muy buen trabajo con el progreso","Si recaes el esfuerzo te ayudara a reponerte",4),
(18,"Un gran camino recorrido haz.","Los mayores dan mayores consejos",4),
(19,"Increible haa sido tu crecimiento.","¿No eres una prodigio?",4),
(20,"A pocos pasos del objetivo","Si no lo intentas hay 0 chances",5),
(21,"¿Cómo van las relaciones?","¿Porq no compartes tu historia?",5),
(22,"¿Te sientes satisfecho?","Cada día deslumbras más confianza",5),
(23,"En serio ya llegaste a aquí","Eres increible",5),
(24,"!Felicidades llegaste a la meta¡","¿Seeguro que necesitabas esto?",5);


INSERT INTO db_mindloose.retos
VALUES
(0,1,'LUGAR:Sentarse en un parque o un jardín durante 30 minutos. '),
(1,1,"LUGAR:Realizar un viaje en transporte público durante 1 hora sin compañía."),
(2,1,'has una videollamada con una persona de tu entera confianza'),
(3,1,'LUGAR:Ir en autobús o en metro un vagón no tan lleno durante 30 minutos sin compañía.'),
(4,1,'LUGAR:Realizar un viaje en taxi o en Uber durante 30 minutos sin compañía.'),
(5,1,'intenta no evitar las situaciones que te causan miedo'),
(6,1,'LUGAR:recoger alguna compra en línea o en pick up.'),
(7,1,'LUGAR:Salga afuera de su casa,y siéntese en su banqueta,y quédese ahí apreciando el panorama por 5 minutos'),
(8,1,'has una lista de todas las cosas que te de pena/verguenza hacer delante cualquier persona'),
(9,1,'LUGAR:en la escuela o trabajo intente de interactuar más con sus compañeros'),
(10,1,'Evita el alcohol y las sustancias recreativas'),
(11,1,'practica el karaoke en tu casa o en tu cuarto '),
(12,1,'No anticipes las situaciones. Reformula un pensamiento más realista para tus miedos irracionales.'),
(13,1,'Deja de buscar el control total de las situaciones, eso no existe. Buscar las salidas de emergencia al llegar a un lugar nuevo, o un hospital cercano, establecer siempre las mismas rutinas, no salir de una zona determinada… son conductas que refuerzan el problema y lo retroalimentan. Libérate de ellas.'),
(14,1,'Trabaja tu autoestima: los problemas de ansiedad suelen ir asociados a la falta de confianza en uno mismo.'),
(15,1,'En la ducha trata de NO pensar en nada, simplementa bañate'),
(16,1,'En un espejo platica contigo mismo frente a este'),
(17,2,'LUGAR:Trate de ser más amables con su familia,si vive solo intente por mandar mensaje a sus amigos más cercanos'),
(18,2,'Pregúntale cómo le ha ido su día a un profesor o a tu compañero de trabajo '),
(19,2,'LUGAR:Empieza subir algo a tus redes sociales, es decir una nota,una historia en ig,o publicar algo en facebook,si no tienes redes sociales instala una'),
(20,2,'LUGAR:Manda una solicitud de amistad/Empieza a seguir a alguien que te caiga bien,pero te de pena hablarle'),
(21,2,'LUGAR:Empieza entablando la conversación con un conocido que no se tan cercano tuyo'),
(22,2,'LUGAR:Dejar de pensar en “el que dirá la gente de mi”,y empezar hacer lo que te gusta'),
(23,2,'LUGAR:empieza a darte cuenta de tus habilidades y en lo que eres bueno'),
(24,2,'LUGAR:empieza a amarte a ti mismo y haz una lista de las cosas que no te gusten de ti,esa lista dividirla en 2 en lo que sí se puede mejorar y en lo que podrías sobrellevar'),
(25,2,'LUGAR:de la lista anterior de las cosas que no te gustan de ti empieza a tomar iniciativa de las cosas que pusiste en mejorar,un ejemplo:”no me gusta mi cuerpo”,la solución:empezar a saltar la cuerda 30 minutos diarios'),
(26,2,'LUGAR:Haz una lista de las cosas que te disgustan o que te incomodan de cualquier situación,de la lista anterior de “las cosas que te incomodan o disgustan”,escribe el por que te disgustan o incomodan y a su vez escribe la solución que creas decente a cada una de estas situaciones'),
(27,2,'Aprende a respirar(Cuando tienes un ataque de ansiedad, uno de tus temores es sentir que te falta el aire, te ahogas y te desmayas, por lo que respiras aceleradamente por miedo a quedarte sin aire.'),
(28,2,'Practica algún deporte(Si hay algo que es muy común en los casos de agorafobia es que tu vida se puede paralizar prácticamente por completo, y tu mundo cambia de la noche a la mañana. No sólo no puedes salir de casa aunque vayas acompañado, sino que cada vez te sientes más limitado y más encerrado dentro de tu zona de confort.'),
(29,2,'Apuntarme a alguna actividad que hacía tiempo que quería hacer'),
(30,2,'lee un libro y platicale el trama y trata de convencer a que lean ese libro a la persona de tu confianza'),
(31,2,'empieza a ser amable diciendo “buenos días,buenas noches,buenas tarde,ten bonito día,gracias,por favor,etc..”,a cualquier persona que te encuentres sea conocida o no,dependiendo la situación este reto lo tienes que aplicar ya diariamente para que se convierta en un hábito'),
(32,2,'LUGAR:Tratar de hacer hablar Con un amigo no tan cercano'),
(33,2,'LUGAR:Iniciar la conversación con un amigo'),
(34,2,'LUGAR:Intentar proponer una salida con un amigo'),
(35,2,'LUGAR:Empieza a mandar mensajes saludando a un amigo/conocido o familiar de tu confianza'),
(36,2,'LUGAR:Empieza a subir fotos de las cosas que te gusten a instagram/Facebook'),
(37,2,'LUGAR:Empieza a interactuar con la mayoría de personas que tengas en tus redes sociales'),
(38,2,'Pregúntale a un policía una dirección o como llegar a algún lado'),
(39,2,'Súbete a algún transporte público y pregunta como cuánto falta para alguna estación'),
(40,2,'Habla con 10 personas diferentes que no tengan alguna conexión'),
(41,2, 'Sal a algun compromiso o a fiesta que tengas NO evites salidas y lugares concurridos '),
(42,3,'LUGAR:Evite depender de otras personas:Puede hacerlo solo o sola. Inténtelo y verá que puede conseguirlo'),
(43,3,'LUGAR:Aceptar la salida de algún Amigo de ir a algun lado'),
(44,3,'LUGAR:Trata de ser espontáneo y no ocultar tu personalidad '),
(45,3,'LUGAR:Si estás en una habitación platicando con amigos,trata de unirte a la conversación y empieza a platicar'),
(46,3,'LUGAR:Rodéate/construye relaciones que te aporten:Al tener una red de amigas/os que te aprecian, te sientes acompañada y con mayor bienestar, ya sabes que al ser humano le encanta pertenecer a un grupo.'),
(47,3,'empieza un hobby que otra persona practique y te llame la atención y pídele consejos o ayuda para aprender sobre este mismo'),
(48,3,'sonriele a las personas con las que hagas contacto visual en la calle'),
(49,3,'hacer ejercicios para vencer la pena,es decir empiece a mirarse al espejo y aceptarse como es'),
(50,3,'empiece a poner límites con cosas que le molesten'),
(51,3,'trata de ser más cariñoso y atento con las personas que consideres importantes'),
(52,3,'abraza a alguien'),
(53,3,'sube algun video a tus redes sociales sobre algo que te guste'),
(54,3,'Ofrece tu lugar a alguien en el transporte público'),
(55,3,'interactúa con la gente de tus redes sociales,(puedes utilizar la caja de preguntas de ig con tus seguidores o esas preguntas anónimas'),
(56,3,'ponte la ropa que menos te guste y sal con ella a lados muy concurrente'),
(57,3,'sal a un parque concurrido durante 1 hora y juega solo cualquier cosa'),
(58,3,'Ve a un parque y en las  canchas ve y  pregunta si te puedes unir a jugar con ellos'),
(59,3,'habla con un vendedor de la calle'),
(60,3,'Anota en una libreta los conflictos que te generan estar en un lugar concurrido'),
(61,3,'Dentro de tu espacio de trabajo entabla conversaciones con tus compañeros'),
(62,4,'LUGAR:comprometerse a realizar cosas concretas:Por ejemplo: “Voy a ir solo o sola al supermercado a hacer la compra” o “Voy a ir solo o sola en autobús”. '),
(63,4,'LUGAR:Hablar enfrente de muchas personas'),
(64,4,'LUGAR:Empezar una conversación con un grupo de personas'),
(65,4,'LUGAR:Hablar sobre lo que sientes con un grupo de amigos'),
(66,4,'habla con la persona que te gusta'),
(67,4,'Ve a una café cuando haya gente y haz como si te faltará dinero y pide un 2 pesos prestados '),
(68,4,'Ve a un parque o a un  café y pregunta a un grupo de amigos si te puedes sentar con ellos'),
(69,4,'invita a salir a la persona que te gusta'),
(70,4,'sal de tu casa con una persona de tu confianza y vayan a comer'),
(71,4,'sal a comer solo a una plaza'),
(72,4,'canta una canción que te guste en frente de muchas personas,o tararea la canción rodeado de muchas personas'),
(73,4,'sube una foto de ti a redes sociales (muestra tu cara totalmente) con una canción que te guste,Y NO LA BORRES'),
(74,4,'Pedir recomendación de música a un grupo de chicos que veas'),
(75,4,'Ofrece tu lugar a alguien en el transporte público'),
(76,4,'Compra dulces y regalaselo s gente que veas que le va mal su día'),
(77,4,'Lleva un juego de dos personas o más y  preguntas a alguien si quiere jugar contigo'),
(78,4,'sal a la calle con ropa que sientes que resalten tus inseguridades y no escuches los malos comentarios,disfruta tu día como normalidad'),
(79,4,'Ve y pidele el numero a una persona que te agrade'),
(80,4,'Sal con tus amigo(s) y organizen una salida y platiquen sobre sus inseguridades '),
(81,4,'Sal con tus amigos o compañeros a un parque de diversiones' );	


ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'n0m3l0';

